spring.application.name=api-gateway

server.port=4020

eureka.client.service-url.defaultZone=http://localhost:4017/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=booking-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://booking-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/bookings/**

spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[2].id=inventory-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://inventory-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/events/**

spring.cloud.gateway.server.webmvc.routes[3].id=order-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webmvc.routes[4].id=ticket-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ticket-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/tickets/**

spring.cloud.gateway.server.webmvc.routes[5].id=venue-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://venue-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/venues/**